In [ ]:
!pip -q install --upgrade tensorflow theano numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 616.4 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 16.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 74.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 50.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 75.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 35.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.


# TensorFlow

In [ ]:
# import
import tensorflow as tf
import numpy as np
a = tf.constant(15)
b = tf.constant(20)
print(a+b)
# input
x = np.random.rand(100).astype(np.float32)
print(x)
# output - observed
y = x * 0.2 + 0.2
# Weight
W = tf.Variable(tf.random.normal([1]))
# bias
b = tf.Variable(tf.zeros([1]))
# Create a function for MSE - mean squared error
def mse_loss():
  ypred = W * x + b
  loss = tf.reduce_mean(tf.square(ypred-y))
  return loss
# Optimizer
optimizer = tf.keras.optimizers.Adam()
# Iterations
for step in range(5000):
  optimizer.minimize(mse_loss,var_list=[W,b])
  if step % 500 == 0:
    print(step, W.numpy(), b.numpy())

tf.Tensor(35, shape=(), dtype=int32)
[7.74489939e-01 2.25407600e-01 7.65461564e-01 6.24047697e-01
 8.10268581e-01 9.42908585e-01 1.86894968e-01 5.60451448e-01
 3.54531594e-02 6.66010737e-01 4.66160268e-01 8.65369916e-01
 4.30715501e-01 9.75579768e-02 4.64527398e-01 2.37948030e-01
 9.66832340e-01 7.19105780e-01 1.59516469e-01 7.02584565e-01
 2.03219406e-06 4.00134206e-01 9.94884491e-01 6.19901776e-01
 5.74302971e-01 7.53329158e-01 5.40019393e-01 7.39051938e-01
 6.34585261e-01 6.33144557e-01 2.83727616e-01 9.48700488e-01
 1.41515031e-01 3.80569279e-01 6.43175185e-01 5.93567193e-01
 6.87473238e-01 2.84711957e-01 1.81945115e-01 6.93619728e-01
 1.42797083e-01 8.92336726e-01 8.84983063e-01 9.19296622e-01
 5.53343117e-01 5.68955600e-01 6.58514023e-01 2.77421594e-01
 8.43951821e-01 3.20635885e-02 2.14290708e-01 9.26266193e-01
 8.27524900e-01 2.94445872e-01 4.63587970e-01 9.74651217e-01
 1.08027525e-01 6.97337747e-01 2.86369383e-01 5.39712548e-01
 7.02889487e-02 9.98138666e-01 8.36756825e-01 7.

# Keras

In [ ]:
from numpy import loadtxt
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
## INPUT Variables ##
# x1 - Number of times pregnant
# x2 - plasma glucose
# x3 - diastolic blood pressure
# x4 - Triceps skin fold thickness
# x5 - 2-hour serum insulin
# x6 - bmi
# x7 - diabetes pedigree function
# x8 - age (yrs)
## Output Variable ##
# Class Variable - 0 or 1
#dataset = loadtxt('/content/sample_data/california_housing_test.csv', delimiter=',')
dataset = pd.read_csv('/content/sample_data/california_housing_test.csv', delimiter=',')

x = dataset.iloc[:, :8]
print(type(x))
print(x.shape)

y = dataset.iloc[:, 8]
print(y)
# Step 2 - Creating or define the Keras Model
# Sequential Model
# Layer1 -> Layer2 -> Layer3

<class 'pandas.core.frame.DataFrame'>
(3000, 8)
0       344700.0
1       176500.0
2       270500.0
3       330000.0
4        81700.0
          ...   
2995    225000.0
2996    237200.0
2997     62000.0
2998    162500.0
2999    500001.0
Name: median_house_value, Length: 3000, dtype: float64


In [ ]:
model = Sequential()
# The model expects row of data with 8 variables
# 12 = nodes
model.add(Dense(12, input_shape=(8,), activation='relu'))
# Hidden Layer
# 8 = nodes
model.add(Dense(8, activation='relu'))
# Output layer
model.add(Dense(1,activation='sigmoid'))
# Step 3 - Compile the Keras model
# loss (error)
# optimizer (adam)
# metrics = accuracy
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#Step 4 - Fit / Train the model
#1 = Epochs - number of iterations / passes
#2 - Batch - sample data
model.fit(x,y, epochs=150, batch_size=5)
# Step 5 - evaluate the model
model.evaluate(x,y)

Epoch 1/150
600/600 [==============================] - 2s 3ms/step - loss: -7557393920.0000 - accuracy: 0.0000e+00
Epoch 2/150
600/600 [==============================] - 2s 3ms/step - loss: -115980615680.0000 - accuracy: 0.0000e+00
Epoch 3/150
600/600 [==============================] - 1s 2ms/step - loss: -528960782336.0000 - accuracy: 0.0000e+00
Epoch 4/150
600/600 [==============================] - 1s 2ms/step - loss: -1410088435712.0000 - accuracy: 0.0000e+00
Epoch 5/150
600/600 [==============================] - 1s 2ms/step - loss: -2811562295296.0000 - accuracy: 0.0000e+00
Epoch 6/150
600/600 [==============================] - 1s 2ms/step - loss: -4766431182848.0000 - accuracy: 0.0000e+00
Epoch 7/150
600/600 [==============================] - 1s 2ms/step - loss: -7328125419520.0000 - accuracy: 0.0000e+00
Epoch 8/150
600/600 [==============================] - 1s 2ms/step - loss: -10519398318080.0000 - accuracy: 0.0000e+00
Epoch 9/150
600/600 [==============================] - 1s 2m

KeyboardInterrupt: ignored

# Theano

In [ ]:
#import theano
#from theano import *
import os
os.environ['THEANO_FLAGS'] = 'device=cpu'

import theano.tensor as T
import numpy as np
import pandas as pd
from theano import function
# scalar variables
v1 = T.dscalar()
v2 = T.scalar()
# subtraction
sres = v1-v2
#add
ares = v1+v2
#convert the results into functions
calcsres = function([v1,v2],sres)
calcares = function([v1,v2],ares)
calcares(12,23)
calcsres(13,12)
x = T.dmatrix('x')
y = T.dmatrix('y')
# addition
z = x+y
func = function([x,y],z)
m1 = [
[1,2],
[3,4]
]
m2 = [
[4,5],
[6,7]
]
func(m1,m2)
# element wise sum
# 00 -> [1+4] -> 5

AttributeError: ignored

# PyTorch

In [ ]:
# Two major objectives of PyTorch
#1. Replacement of Numpy to use the power of GPUs and other accelerators
#2. Automatic Differentiation Library helps in implementation of Neural Networks

# Feed Forward --> first stage
# Back Propagation --> second stage (differentiation)
# Tensors - Special Data Structures
# similar to an array, matrices
# similar to Numpy ndarrays
import torch
import numpy as np
# Tensor Initialization
### multiple ways
### 1 - using data
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(type(x_data))
### 2 - using numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))
### 3 - using another tensor
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)
#### more ways to create tensors
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device
# Tensor Operations
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
else:
  tensor = tensor.to("cpu")
print("Device tensor is stored in", tensor.device)
# Indexing, Slicing
tensor = torch.ones(4,4)

print(tensor)
print(tensor)
tensor1 = torch.zeros(4,4)
print(tensor1)
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)
# Multiply Operation
tensor.mul(tensor1)
tensor * tensor1
tensor.T
# inplace - change the original tensor
tensor.add_(3)
print(tensor)
# from tensor to numpy
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.6241, 0.3350],
        [0.0036, 0.3608]])
tensor([[0.5284, 0.6351, 0.0488],
        [0.3911, 0.4460, 0.6695]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.9587, 0.9318, 0.1277, 0.5099],
        [0.9486, 0.3291, 0.4586, 0.4282],
        [0.4314, 0.3750, 0.4880, 0.4748]])
Device tensor is stored in cpu
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0.,